name: Build and Publish image to Docker Hub
on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "master" ]    
    paths:
      - 'dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./ -t xbtdevel/example:latest 
      - name: push image to docker hub
        run: |
          docker login -u xbtdevel -p ${{secrets.RENDI_DOCKER_TEST_KEY}}  
          docker push xbtdevel/example:latest 
